loglevel: debug
port: 8080
webport: 8081
intervalminutes: 1
certificates:
    - dns: remote.agventuresllc.net
    - dns: remote.cocalicobiologicals.com
    - dns: ctx.grapekbates.com
    - dns: ctx.landtransferco.com
    - dns: aa.lh-inc.com
    - dns: cw.nsta.io
    - dns: screen.nsta.io
    - dns: remote.snavelysmill.com
    - dns: aa.snavelysmill.com
    - dns: remote.theoldcountrystore.com
    - dns: aa.classicpl.com
    - dns: pw.olmsted.cc