
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cert-checker.fullname" . }}
  labels:
    {{- include "cert-checker.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cert-checker.fullname" . }}
  endpoints:
  - port: http
