apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-checker.fullname" . }}
  labels:
    {{- include "cert-checker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.uiService.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port }}
      targetPort: metrics-http
      protocol: TCP
      name: metrics-http
  selector:
    {{- include "cert-checker.selectorLabels" . | nindent 4 }}
