apiVersion: v1
kind: Namespace
metadata:
  name: cert-checker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-checker
  namespace: cert-checker
---
apiVersion: v1
kind: Service
metadata:
  name: cert-checker
  namespace: cert-checker
  labels:
    app: cert-checker
spec:
  selector:
    app: cert-checker
  ports:
    - protocol: TCP
      name: web
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cert-checker
  name: cert-checker
  namespace: cert-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-checker
  template:
    metadata:
      labels:
        app: cert-checker
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        enable.cert-checker.io/cert-checker: "true"
    spec:
      serviceAccountName: cert-checker
      containers:
      - image: mogensen/cert-checker:v0.0.1
        command: ["/app/cert-checker", "-c", "/data/config.yaml"]
        # imagePullPolicy: Always
        ports:
        - containerPort: 8080
        name: cert-checker
        volumeMounts:
        - name: config-volume
          mountPath: /data/
      volumes:
        - name: config-volume
          configMap:
            name: cert-checker
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cert-checker
  namespace: cert-checker
data:
  config.yaml: |
    loglevel: debug
    intervalminutes: 1
    certificates:
        - dns: google.com
        - dns: example.com
        - dns: expired.badssl.com
        - dns: wrong.host.badssl.com
        - dns: untrusted-root.badssl.com
        - dns: self-signed.badssl.com
        - dns: revoked.badssl.com
        - dns: dh480.badssl.com
        - dns: dh512.badssl.com
        - dns: null.badssl.com
        - dns: rc4-md5.badssl.com
        - dns: rc4.badssl.com
