---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-checker
  labels:
    app.kubernetes.io/name: cert-checker
    app.kubernetes.io/instance: cert-checker
    app.kubernetes.io/version: "v0.0.4"
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-checker
  endpoints:
  - port: metrics-http
