name: Helm Documentation
on: push
jobs:
  documentation:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
      - name: Install Dependencies
        run: |
          apk add jq git curl
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Install Helm Docs
        run: |
          curl -s -L -o /usr/local/bin/helm-docs.tar.gz "https://github.com/norwoodj/helm-docs/releases/download/$(curl --silent "https://api.github.com/repos/norwoodj/helm-docs/releases/latest" | jq -r .tag_name)/helm-docs_$(curl --silent "https://api.github.com/repos/norwoodj/helm-docs/releases/latest" | jq -r .tag_name | cut -d "v" -f2-)_Linux_x86_64.tar.gz"
          cd /usr/local/bin/ && tar xfv helm-docs.tar.gz
          chmod +x ./helm-docs
      - name: Update Documentation
        run: |
          git status
          ## Generate Documentation
          helm-docs
          ## Push Changes
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -sam "Update Documentation" || true
          git push || true
