name: Release with goreleaser
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'
      -
        name: Release via goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
